### ISSUE TITLE
Switch the event_id for the event_title in Event Pivot

### ISSUE THREAD

**Issue by jromeraa** [eileenmcnaughton/nz.co.fuzion.extendedreport#154]
### **Overview**
Switch the event id for the event title in Event Pivot included the link to see it.

### **Before:**
![imagen](https://user-images.githubusercontent.com/45352121/49069318-48936400-f229-11e8-91de-9d87eb7d662c.png)
### **After:**
![imagen](https://user-images.githubusercontent.com/45352121/49069238-0ff38a80-f229-11e8-824b-4e94b81dcd16.png)

**Comment by jromeraa** [comment]
I upgraded the code. 

https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/pull/155/commits/c894567d27094dbdd62ee6affcc7b96f8a54f0e3

**Comment by francescbassas** [comment]
Thanks @jromeraa and @litelo22 to this improvement.

@eileenmcnaughton our trainee-students have been working on this enhancement that helps our users to see the participant status of the current events and to be able to do a better follow-up.

**Comment by eileenmcnaughton** [comment]
@francescbassas @jromeraa so this is a good point. What I have been doing is have the event id show as a number with a link - because often people DO want to know the number. I feel like often what people want is title with a link - I've been pondering this for a while - I think ideally it would be more like views & people could choose what links go on what fields - but that is a bigger thing!

I'm a little reluctant to obscure the event id for when people do want it  - I feel like having both the  title field & the id field linked through would give the link option without hiding the id for people who want that info

**Comment by jromeraa** [comment]
We created a column named Event Title, in the second place on the table.
https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/pull/162

**Comment by francescbassas** [comment]
@eileenmcnaughton how do you see changes proposed for @jromeraa? Can it be integrated into the extension?

**Comment by francescbassas** [comment]
@jromeraa this feature it's covered by recent extension changes. You can close this issue.

**Comment by francescbassas** [comment]
Thanks @eileenmcnaughton!

**Comment by eileenmcnaughton** [comment]
TBH I can't keep track of these - I just saw you say close so I did :-)
