### ISSUE TITLE
Small notice problem

### ISSUE THREAD

**Issue by magnolia61** [eileenmcnaughton/nz.co.fuzion.extendedreport#17]
Probably a small notice problem. I know you hate these too :-)

Notice: Undefined index: fields in CRM_Extendedreport_Form_Report_ExtendedReport->select() (line 418 of /home/ozk/domains/ourdomain.nl/public_html/crm/sites/all/modules/civicrm_extensions/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/ExtendedReport.php).

**Comment by magnolia61** [comment]
And another one:
Notice: Undefined index: htmlType in CRM_Extendedreport_Form_Report_ExtendedReport->addColumnAggregateSelect() (line 543 of /home/ozk/domains/ourdomain.nl/public_html/crm/sites/all/modules/civicrm_extensions/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/ExtendedReport.php).

**Comment by magnolia61** [comment]
And another one, for reference: no hurries, but good to know: Shown in the /civicrm/admin/extensions 
Warning: Invalid argument supplied for foreach() in _extendedreport_civix_civicrm_managed() (line 155 of /home/ozk/domains/ourdomain.nl/public_html/crm/sites/all/modules/civicrm_extensions/nz.co.fuzion.extendedreport/extendedreport.civix.php).

**Comment by eileenmcnaughton** [comment]
I think the code has changed enough since this that it might not be relevant? The line numbers have changed at any rate.

I've hit one at Notice: Undefined index: values in addColumnAggregateSelect() (line 698 of /home/vagrant/civicrm-buildkit/build/drupal-demo/sites/default/ext/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/ExtendedReport.php). =>  which I'm fixing

**Comment by eileenmcnaughton** [comment]
I'm closing this as I think the prior notices are not the same as they were (at least on master) & it makes more sense to re-open tickets based on latest status if required
