### ISSUE TITLE
Criteria.tpl is unnecessary

### ISSUE THREAD

**Issue by jmcclelland** [eileenmcnaughton/nz.co.fuzion.extendedreport#21]
It seems to be included in reportbase - which is required by extendedreport, so including it in extendedreport duplicates that file.

**Comment by jmcclelland** [comment]
See: https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/pull/22

**Comment by eileenmcnaughton** [comment]
NB - reportbase isn't required by extended report & I've started to drift back to just using extended reports since powerbase reports no longer relies on reportbase & I was just maintaining both

**Comment by eileenmcnaughton** [comment]
I've gone the other way on this & ported a swag of 4.6 work I did into this extension - on the bright side once 4.6 is the min version I should be able to clean it out again. The 4.6 stuff includes the 4.6 criteria.tpl. I'll probably have to fix some more as I'm guessing I might have lost some intentional overrides in the process.
