### ISSUE TITLE
Participant Extended Report- Fails when filtering relationship types

### ISSUE THREAD

**Issue by alarmingcod** [eileenmcnaughton/nz.co.fuzion.extendedreport#218]
Hi Eileen,

I've built a participant report to link to contacts' related organisations. When I try to filter by relationship type (particpants with multiple relationship types are showing multiple times) I get a db error message. SQL Error from Drupal Watchdog attached.

Using  D7, Civi 5.3.1 Extendreports 3.5

Any feedback/ advice appreciated.

Cheers

Craig

[FatalErrorLog.txt](https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/files/2869621/FatalErrorLog.txt)

**Comment by eileenmcnaughton** [comment]
I have been working on version 4.0 for a while - quite a bit of restructuring - It may fix it - it is not auto-downloadable for less than 5.10 but there will be a 5.10.x security release soon so I expect you'll be on that soon anyway. 

I figured since I'm not planning to fix anything on 3.5 anymore I should drop 4.0 - I was going to keep it in testing longer - but since there is a t least one key bug on 3.5 putting it out makes more sense.

4.0 has a lot more unit testing...

**Comment by alarmingcod** [comment]
Thank you for the update.

Have been using the extension more recently and love the added functionality it gives.
