### ISSUE TITLE
Pivot tables show "field not found" if pivoting on a custom field

### ISSUE THREAD

**Issue by MegaphoneJon** [eileenmcnaughton/nz.co.fuzion.extendedreport#366]
`CRM_Extendedreport_Form_Report_ExtendedReport::extendedCustomDataFrom()` adds custom field tables to the `from` clause by reviewing various properties of the object to see if custom fields are needed to build the query.  However, it doesn't check the pivot columns on pivot table reports.

I have a fix being tested by my client, I'll submit it after QA is complete.

**Comment by eileenmcnaughton** [comment]
thanks @MegaphoneJon

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon I had to revert this as it caused failing tests which I didn't pick up

**Comment by eileenmcnaughton** [comment]
@MegaphoneJon  this https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/pull/386 might tangentially address this issue

**Comment by eileenmcnaughton** [comment]
With recent commits this seems to work - I will tag a new release next week probably - I tagged one this week just to override the recent one due to the url issue but the next one will be against 5.28 & will have all these join fixes

<img width="816" alt="Screen Shot 2020-07-12 at 2 12 59 PM" src="https://user-images.githubusercontent.com/336308/87237392-d301f900-c449-11ea-9146-2066311137d1.png">
