### ISSUE TITLE
Show premiums in report

### ISSUE THREAD

**Issue by andyburnsco** [eileenmcnaughton/nz.co.fuzion.extendedreport#436]
We would like to fund this improvement. Please contact on Mattermost: https://chat.civicrm.org/civicrm/messages/@andyburns

Premiums info doesn't show in _CRM_Extendedreport_Form_Report_Contribute_Contributions_ report.

It does show in Contribution and Membership Details report: https://civicrm.stackexchange.com/questions/2554/reporting-on-premium-fulfillment (_CRM_Report_Form_Member_ContributionDetail_)

Fields to include:

- Premium
- Premium option
- Premium Fulfilled date

**Comment by andyburnsco** [comment]
I understand search kit may be the way forward but I would prefer to do it this way as of now.

**Comment by andyburnsco** [comment]
Also add to the list these fields:

- Individual prefix
- Individual suffix

**Comment by eileenmcnaughton** [comment]
I added these to the Contributions report & bookkeeping report (the extra contact fields are on all reports). The slightly annoying thing is the Product & the linking of the product to a contribution have separate accordians because they are separate tables. I haven't spotted an easy way to fix.

I didn't go through all the reports but detail extended probably would need a bit of clean up before adding more tables

**Comment by andyburnsco** [comment]
Tested and works
