### ISSUE TITLE
Bookkeeping Extended Report - Not Adding Up Line Items Correctly.

### ISSUE THREAD

**Issue by mrsrjd** [eileenmcnaughton/nz.co.fuzion.extendedreport#48]
Within the Bookkeeping with extra fields template, if I use the group by function, I do not receive the proper line totals (they are not adding up). 

For instance, if I group by line item financial type, it groups it correctly, but the line totals are wrong: 
![bookkeepingreport](https://cloud.githubusercontent.com/assets/17750219/13646956/d4abe7ac-e5ff-11e5-8146-3839aae669d3.png)

If I use the Contribution Based Line Item report, the totals are accurate. However, I need the account code on this report, which is why I was using the bookkeeping report. 
![bookkeepingreport2](https://cloud.githubusercontent.com/assets/17750219/13646957/d4ac5ed0-e5ff-11e5-9b2e-46a32fdf5930.png)

**Comment by joannechester** [comment]
@mrsjd,  I add my  account codes to the financial account names as a work-around for the line item report. Perhaps that would work for you also.

**Comment by ryeradio** [comment]
I have identified the reason the participant count did not work is because I did not have that filled in on my price sets. Now that I updated that it is closer, but it is still off. I have my event set to allow multiple registrations. If someone registers another person, that person is not showing on the report. Do you know why that might be? For example Bob registered for himself and Sally. Bob is on the report and Sally is not. But technically they are both registered and paid for.

**Comment by eileenmcnaughton** [comment]
Let me know if this patch works for you

**Comment by eileenmcnaughton** [comment]
NB if it does seem all good I'll tag a release - I did a reasonable restructure to get to this

**Comment by eileenmcnaughton** [comment]
Closing - seems to be been patched a while back
