### ISSUE TITLE
Line Item report: out-of-criteria results showing in report output, for membership contributions

### ISSUE THREAD

**Issue by twomice** [eileenmcnaughton/nz.co.fuzion.extendedreport#52]
Steps to reproduce:
1. Create a contact named "Bob Example" with a membership requiring payment.
2. Create a payment record for that membership, with a received date of 2015-01-15.
3. Create another payment record for that membership, with a received date of 2016-01-15, and (for the sake of demonstration) with an amount that's a dollar or two more than it needs to be.
4. Create a new report based on "Extended Report - Price Set Line Items" template, and set the Received Date filter to "between 2016-01-01 and 2016-01-31". Preview the report.
5. Observe that both of Bob Example's contributions (one with the required amount, and one with the 'dollar or two more' amount) are both listed in the report output (albeit one of them has some incorrect information, such as Received Date).

**Comment by twomice** [comment]
This may be a duplicate of #42 .

**Comment by twomice** [comment]
The cause appears to be in this SQL query https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/blob/master/CRM/Extendedreport/Form/Report/ExtendedReport.php#L5843 which is joining line items to contributions through the membership table, thus glomming all line items for a single membership into a single contribution, even if they were line items from several different contributions.

**Comment by twomice** [comment]
TODO: Add checks for pre-4.5 versions.

**Comment by robbrandt** [comment]
Hi.  Thanks for this.  This solves the problem for me as well.  @eileenmcnaughton Is there a reason this pull request hasn't been completed yet?

**Comment by robbrandt** [comment]
I also seem to be having this issue with contributions in general.

**Comment by robbrandt** [comment]
I now have my data reporting correctly, and the "fix" was to comment out 
CRM_Core_DAO::executeQuery($insertContributionRecordsSql);
The temporary table was actually populating the entries twice; once with the contributions and once with the memberships.  Since @twomice's fix was quite generic (not restricted to memberships per se) it seemed to be doing the same thing as inserting the Contribution line items (and memberships ARE contributions) so.... disabling the Contribution insert makes sense.  Probably makes more sense to move the membership query to contributions and then disable membership (so that the function matches the name) but I need some feedback from @eileenmcnaughton before making final changes.

Our transactions are complex, and this may be why I am seeing bad stuff where others don't.  For us membership renewal season is also donation solicitation time.  It is totally normal for a single transaction to include a membership, an endowment donation, gift memberships, and donations to special funds.

So the remaining question is, "does my fix screw up other uses of this extension?".  Eileen?

**Comment by eileenmcnaughton** [comment]
I've pulled out that sql in 2 places - although not  necessarily all yet...

**Comment by eileenmcnaughton** [comment]
There are a couple of fixes on this & no further reports of issues so I'm closing now.
