### ISSUE TITLE
Error in Extended Report - Relationships

### ISSUE THREAD

**Issue by Dennisdd** [eileenmcnaughton/nz.co.fuzion.extendedreport#84]
Dear Eileen,

thank you for all your work on this extension, it is fantastic!

I have some errors when I try to set up a new report based on the Contact Extended Report - Relationships template.  
I have added one single custom field (university) in the individual contacts. If I enter something for this custom field in the filter, it just gives an error when running the report:  
"Sorry but we are not able to provide this at the moment.
DB Error: syntax error"

I have tried changing the custom field from select to a simple text field but it still throws the same error when I use it in the filter.

Your help is much appreciated!

Dennis

**Comment by eileenmcnaughton** [comment]
I had a look & I could replicate this. Unfortunately the fix is going to take some thought. There was a bunch of effort that went into how to expose custom fields on multiple entities & allow the row order to be sorted on an earlier version of CiviCRM. Unfortunately it didn't quite survive the core change to using the Select 2 widget & was fundamentally pretty un-robust. 

I'm going to need to set aside enough time to solve this problem properly, not quite sure when I'll be able to do that

**Comment by Dennisdd** [comment]
Thanks for the quick reply, Eileen, if there is anything I can do to support, then just let me know. I am not really a programmer but might support in testing, for example.

**Comment by eileenmcnaughton** [comment]
I've just pushed a fix  - hopefully it works
